### PR TITLE
Simplify hostname parsing

### PR DESCRIPTION
**Pull request by messense**

### CODE REVIEW

**Comment by fafhrd91** [comment]
does it work? `addrinfo::lookup` accepts `Option<String>`

**Comment by messense** [comment]
https://doc.rust-lang.org/std/option/enum.Option.html#method.map

`map` converts an `Option<T>` to `Option<U>` by applying a function to a contained value.

so it returns an `Option<String>`

**Comment by messense** [comment]
Test passes except #16

**Comment by fafhrd91** [comment]
ok, good. could you change host in other places as well. `getaddrinfo`, `create_server`

those tests just for `http/decoder.rs`

**Comment by messense** [comment]
Sorry I not sure where those are, I am new to this awesome project.

**Comment by fafhrd91** [comment]
other place is in `create_server_helper`.

`getattrinfo` uses different params

**Comment by messense** [comment]
I think I already changed that: https://github.com/PyO3/async-tokio/pull/17/files#diff-50d7cf24abb3470174843ee1af4ccd56R923

**Comment by fafhrd91** [comment]
oh! sorry. thanks!

**Comment by fafhrd91** [comment]
@messense hey, would you do more work on async-tokio?

**Comment by messense** [comment]
I would like to when I understand it more.

Add some more docs on how to contribute to it and setup Travis CI would be great.

**Comment by fafhrd91** [comment]
travis and docs will take some time, I am very busy at the moment.

but simplest and isolated task is to extend functionality of PyBytes. make it more bytes like. for example "split()" method same as this https://docs.python.org/3/library/stdtypes.html#bytes.split

**Comment by messense** [comment]
Please open some issues and tag them `easy`/`medium`/`hard` etc. so that others can easily get involved.

**Pull request merged**
